version: "3.9"

services:
  lab-api1:
    build: .
    image: thescarletarrow/lab-api:0.0.5
    restart: always
#    ports:
#      - "8081:8080"
  lab-api2:
    build: .
    image: thescarletarrow/lab-api:0.0.5
    restart: always
#    ports:
#      - "8082:8080"
  redis:
    build: .
    image: redis
    ports:
      - "6379:6379"
    restart: always
  balancer:
    image: nginx
    volumes:
      - ./Balancer/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:8080"
    depends_on:
      - lab-api1
      - lab-api2

