version: "3.9"

services:
  lab-api:
    build: .
    image: thescarletarrow/lab-api:tagname
    restart: always
    ports:
      - "8080:8080"
    environment:
      appid:
        ${appid}
      site:
        ${site}